using System.Numerics;
using PicoMoldForge.Core.BooleanGeometry;
using PicoMoldForge.Core.Parting;
using PicoMoldForge.PicoGK.Runtime;
using PicoLibrary = global::PicoGK.Library;
using PicoMesh = global::PicoGK.Mesh;
using PicoVoxels = global::PicoGK.Voxels;

namespace PicoMoldForge.PicoGK.BooleanGeometry;

public sealed class PicoBooleanCavityCoreSplitter
{
    public BooleanCavityCoreSplitResult Generate(BooleanCavityCoreSplitRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var validationErrors = request.Validate();

        if (validationErrors.Count > 0)
        {
            throw new ArgumentException(
                "Invalid boolean cavity/core split request: " + string.Join(" ", validationErrors),
                nameof(request));
        }

        var resolvedSourcePath = Path.GetFullPath(request.SourcePath);
        var resolvedOutputDirectory = Path.GetFullPath(request.OutputDirectory);

        if (!File.Exists(resolvedSourcePath))
        {
            throw new FileNotFoundException("Source STL file was not found.", resolvedSourcePath);
        }

        Directory.CreateDirectory(resolvedOutputDirectory);

        return PicoGkTaskRunner.Run(() =>
        {
            var library = PicoLibrary.oLibrary();

            var sourceMesh = PicoMesh.mshFromStlFile(
                resolvedSourcePath,
                default,
                1.0f,
                null,
                library);

            try
            {
                using var partVoxels = new PicoVoxels(in sourceMesh);

                var coreBounds = CreateHalfBounds(
                    request.BlockBounds,
                    request.SplitAxis,
                    request.PartingPlaneOffsetMm,
                    MoldHalfKind.CoreSide);

                var cavityBounds = CreateHalfBounds(
                    request.BlockBounds,
                    request.SplitAxis,
                    request.PartingPlaneOffsetMm,
                    MoldHalfKind.CavitySide);

                var coreSide = GenerateHalf(
                    library,
                    partVoxels,
                    coreBounds,
                    MoldHalfKind.CoreSide,
                    Path.Combine(resolvedOutputDirectory, "BooleanCoreSide.stl"));

                var cavitySide = GenerateHalf(
                    library,
                    partVoxels,
                    cavityBounds,
                    MoldHalfKind.CavitySide,
                    Path.Combine(resolvedOutputDirectory, "BooleanCavitySide.stl"));

                var warnings = new[]
                {
                    "BooleanCoreSide.stl and BooleanCavitySide.stl are generated by voxel boolean subtraction from split mold-block halves.",
                    "This is a preliminary functional split proof, not a production-ready mold split.",
                    "No shutoff surfaces, runner/gate/sprue, side actions, slides, lifters, cooling subtraction, or manufacturability certification is performed in Phase 13A."
                };

                return new BooleanCavityCoreSplitResult(
                    IsSuccessful: true,
                    SplitAxis: request.SplitAxis,
                    PartingPlaneOffsetMm: request.PartingPlaneOffsetMm,
                    CoreSide: coreSide,
                    CavitySide: cavitySide,
                    Warnings: warnings);
            }
            finally
            {
                sourceMesh.Dispose();
            }
        }, request.VoxelSizeMm);
    }

    private static BooleanMoldHalfGenerationResult GenerateHalf(
        PicoLibrary library,
        PicoVoxels partVoxels,
        MoldBlockBounds bounds,
        MoldHalfKind kind,
        string outputPath)
    {
        using var blockMesh = CreateBlockMesh(bounds, library);
        using var blockVoxels = new PicoVoxels(in blockMesh);
        using var halfVoxels = blockVoxels.voxBoolSubtract(in partVoxels);

        halfVoxels.CalculateProperties(out var remainingVolume, out _);

        using var halfMesh = halfVoxels.mshAsMesh();

        halfMesh.SaveToStlFile(
            outputPath,
            PicoMesh.EStlUnit.MM,
            null,
            1.0f);

        var outputInfo = new FileInfo(outputPath);

        return new BooleanMoldHalfGenerationResult(
            Kind: kind,
            OutputPath: outputPath,
            OutputFileSizeBytes: outputInfo.Length,
            Bounds: bounds,
            RemainingVolumeCubicMm: remainingVolume,
            DiagnosticTriangleCount: halfMesh.nTriangleCount(),
            DiagnosticVertexCount: halfMesh.nVertexCount());
    }

    private static MoldBlockBounds CreateHalfBounds(
        MoldBlockBounds fullBounds,
        PartingAxis splitAxis,
        decimal offset,
        MoldHalfKind kind)
    {
        var isCoreSide = kind == MoldHalfKind.CoreSide;

        return splitAxis switch
        {
            PartingAxis.X => isCoreSide
                ? fullBounds with { MaxXmm = offset }
                : fullBounds with { MinXmm = offset },

            PartingAxis.Y => isCoreSide
                ? fullBounds with { MaxYmm = offset }
                : fullBounds with { MinYmm = offset },

            PartingAxis.Z => isCoreSide
                ? fullBounds with { MaxZmm = offset }
                : fullBounds with { MinZmm = offset },

            _ => throw new ArgumentOutOfRangeException(nameof(splitAxis), splitAxis, "Unsupported parting axis.")
        };
    }

    private static PicoMesh CreateBlockMesh(MoldBlockBounds bounds, PicoLibrary library)
    {
        var mesh = new PicoMesh(library);

        var minX = Convert.ToSingle(bounds.MinXmm);
        var minY = Convert.ToSingle(bounds.MinYmm);
        var minZ = Convert.ToSingle(bounds.MinZmm);
        var maxX = Convert.ToSingle(bounds.MaxXmm);
        var maxY = Convert.ToSingle(bounds.MaxYmm);
        var maxZ = Convert.ToSingle(bounds.MaxZmm);

        AddTriangle(mesh, minX, minY, minZ, maxX, maxY, minZ, maxX, minY, minZ);
        AddTriangle(mesh, minX, minY, minZ, minX, maxY, minZ, maxX, maxY, minZ);

        AddTriangle(mesh, minX, minY, maxZ, maxX, minY, maxZ, maxX, maxY, maxZ);
        AddTriangle(mesh, minX, minY, maxZ, maxX, maxY, maxZ, minX, maxY, maxZ);

        AddTriangle(mesh, minX, minY, minZ, maxX, minY, minZ, maxX, minY, maxZ);
        AddTriangle(mesh, minX, minY, minZ, maxX, minY, maxZ, minX, minY, maxZ);

        AddTriangle(mesh, minX, maxY, minZ, maxX, maxY, maxZ, maxX, maxY, minZ);
        AddTriangle(mesh, minX, maxY, minZ, minX, maxY, maxZ, maxX, maxY, maxZ);

        AddTriangle(mesh, minX, minY, minZ, minX, minY, maxZ, minX, maxY, maxZ);
        AddTriangle(mesh, minX, minY, minZ, minX, maxY, maxZ, minX, maxY, minZ);

        AddTriangle(mesh, maxX, minY, minZ, maxX, maxY, minZ, maxX, maxY, maxZ);
        AddTriangle(mesh, maxX, minY, minZ, maxX, maxY, maxZ, maxX, minY, maxZ);

        return mesh;
    }

    private static void AddTriangle(
        PicoMesh mesh,
        float ax,
        float ay,
        float az,
        float bx,
        float by,
        float bz,
        float cx,
        float cy,
        float cz)
    {
        var a = new Vector3(ax, ay, az);
        var b = new Vector3(bx, by, bz);
        var c = new Vector3(cx, cy, cz);

        mesh.nAddTriangle(in a, in b, in c);
    }
}