using System.Numerics;
using PicoMoldForge.Core.BooleanGeometry;
using PicoMoldForge.PicoGK.Runtime;
using PicoLibrary = global::PicoGK.Library;
using PicoMesh = global::PicoGK.Mesh;
using PicoVoxels = global::PicoGK.Voxels;

namespace PicoMoldForge.PicoGK.BooleanGeometry;

public sealed class PicoBooleanCavityGenerator
{
    public BooleanCavityGenerationResult Generate(BooleanCavityGenerationRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var validationErrors = request.Validate();

        if (validationErrors.Count > 0)
        {
            throw new ArgumentException(
                "Invalid boolean cavity generation request: " + string.Join(" ", validationErrors),
                nameof(request));
        }

        var resolvedSourcePath = Path.GetFullPath(request.SourcePath);
        var resolvedOutputDirectory = Path.GetFullPath(request.OutputDirectory);

        if (!File.Exists(resolvedSourcePath))
        {
            throw new FileNotFoundException("Source STL file was not found.", resolvedSourcePath);
        }

        Directory.CreateDirectory(resolvedOutputDirectory);

        var outputPath = Path.Combine(resolvedOutputDirectory, "BooleanCavity.stl");

        return PicoGkTaskRunner.Run(() =>
        {
            var library = PicoLibrary.oLibrary();

            var sourceMesh = PicoMesh.mshFromStlFile(
                resolvedSourcePath,
                default,
                1.0f,
                null,
                library);

            try
            {
                using var partVoxels = new PicoVoxels(in sourceMesh);
                using var blockMesh = CreateBlockMesh(request.BlockBounds, library);
                using var blockVoxels = new PicoVoxels(in blockMesh);

                blockVoxels.CalculateProperties(out var blockVolume, out _);

                using var cavityVoxels = blockVoxels.voxBoolSubtract(in partVoxels);
                cavityVoxels.CalculateProperties(out var cavityVolume, out _);

                using var cavityMesh = cavityVoxels.mshAsMesh();

                cavityMesh.SaveToStlFile(
                    outputPath,
                    PicoMesh.EStlUnit.MM,
                    null,
                    1.0f);

                var outputInfo = new FileInfo(outputPath);

                var warnings = new List<string>
                {
                    "BooleanCavity.stl is generated by PicoGK voxel boolean subtraction of the part from a mold block.",
                    "This is a functional boolean geometry proof, not a production-certified cavity.",
                    "No parting split, shutoff surfaces, runner/gate/sprue, draft correction, or manufacturability certification is performed in Phase 12B."
                };

                if (cavityVolume >= blockVolume)
                {
                    warnings.Add("PicoGK reported cavity volume greater than or equal to block volume; volume is retained as diagnostic data and not used as the Phase 12B pass condition.");
                }

                return new BooleanCavityGenerationResult(
                    IsSuccessful: true,
                    OutputPath: outputPath,
                    OutputFileSizeBytes: outputInfo.Length,
                    BlockVolumeCubicMm: blockVolume,
                    CavityVolumeCubicMm: cavityVolume,
                    DiagnosticTriangleCount: cavityMesh.nTriangleCount(),
                    DiagnosticVertexCount: cavityMesh.nVertexCount(),
                    Warnings: warnings);
            }
            finally
            {
                sourceMesh.Dispose();
            }
        }, request.VoxelSizeMm);
    }

    private static PicoMesh CreateBlockMesh(MoldBlockBounds bounds, PicoLibrary library)
    {
        var mesh = new PicoMesh(library);

        var minX = Convert.ToSingle(bounds.MinXmm);
        var minY = Convert.ToSingle(bounds.MinYmm);
        var minZ = Convert.ToSingle(bounds.MinZmm);
        var maxX = Convert.ToSingle(bounds.MaxXmm);
        var maxY = Convert.ToSingle(bounds.MaxYmm);
        var maxZ = Convert.ToSingle(bounds.MaxZmm);

        AddTriangle(mesh, minX, minY, minZ, maxX, maxY, minZ, maxX, minY, minZ);
        AddTriangle(mesh, minX, minY, minZ, minX, maxY, minZ, maxX, maxY, minZ);

        AddTriangle(mesh, minX, minY, maxZ, maxX, minY, maxZ, maxX, maxY, maxZ);
        AddTriangle(mesh, minX, minY, maxZ, maxX, maxY, maxZ, minX, maxY, maxZ);

        AddTriangle(mesh, minX, minY, minZ, maxX, minY, minZ, maxX, minY, maxZ);
        AddTriangle(mesh, minX, minY, minZ, maxX, minY, maxZ, minX, minY, maxZ);

        AddTriangle(mesh, minX, maxY, minZ, maxX, maxY, maxZ, maxX, maxY, minZ);
        AddTriangle(mesh, minX, maxY, minZ, minX, maxY, maxZ, maxX, maxY, maxZ);

        AddTriangle(mesh, minX, minY, minZ, minX, minY, maxZ, minX, maxY, maxZ);
        AddTriangle(mesh, minX, minY, minZ, minX, maxY, maxZ, minX, maxY, minZ);

        AddTriangle(mesh, maxX, minY, minZ, maxX, maxY, minZ, maxX, maxY, maxZ);
        AddTriangle(mesh, maxX, minY, minZ, maxX, maxY, maxZ, maxX, minY, maxZ);

        return mesh;
    }

    private static void AddTriangle(
        PicoMesh mesh,
        float ax,
        float ay,
        float az,
        float bx,
        float by,
        float bz,
        float cx,
        float cy,
        float cz)
    {
        var a = new Vector3(ax, ay, az);
        var b = new Vector3(bx, by, bz);
        var c = new Vector3(cx, cy, cz);

        mesh.nAddTriangle(in a, in b, in c);
    }
}