using Core = PicoMoldForge.Core;
using PicoMoldForge.Core.BooleanGeometry;
using PicoMoldForge.Core.CavityCore;
using PicoMoldForge.Core.Cooling;
using PicoMoldForge.Core.DfAM;
using PicoMoldForge.Core.Exports;
using PicoMoldForge.Core.Lattice;
using PicoMoldForge.Core.MoldSystems;
using PicoMoldForge.PicoGK.Analysis;
using PicoMoldForge.PicoGK.BooleanGeometry;
using PicoMoldForge.PicoGK.CavityCore;
using PicoMoldForge.PicoGK.Cooling;
using PicoMoldForge.PicoGK.Exports;
using PicoMoldForge.PicoGK.GateSystem;
using PicoMoldForge.PicoGK.Lattice;
using PicoMoldForge.PicoGK.MoldSystems;

namespace PicoMoldForge.Generator;

public sealed class GeneratorPipelineRunner
{
    public GeneratorPipelineRunResult Run(GeneratorPipelineInput input)
    {
        ArgumentNullException.ThrowIfNull(input);

        Directory.CreateDirectory(input.ResolvedOutputDirectory);

        var voxelSizeMm = Convert.ToSingle(input.Config.VoxelResolutionMm);
        var shrinkageRate = Convert.ToDecimal(input.Config.Material.ShrinkageRate);

        var diagnosticMeshPath = Path.Combine(input.ResolvedOutputDirectory, "DiagnosticMesh.stl");
        var booleanCavityPath = Path.Combine(input.ResolvedOutputDirectory, "BooleanCavity.stl");
        var booleanCoreSidePath = Path.Combine(input.ResolvedOutputDirectory, "BooleanCoreSide.stl");
        var booleanCavitySidePath = Path.Combine(input.ResolvedOutputDirectory, "BooleanCavitySide.stl");
        var coolingDiagnosticPath = Path.Combine(input.ResolvedOutputDirectory, "CoolingDiagnostic.stl");
        var latticeDiagnosticPath = Path.Combine(input.ResolvedOutputDirectory, "LatticeDiagnostic.stl");
        var moldSystemDiagnosticPath = Path.Combine(input.ResolvedOutputDirectory, "MoldSystemDiagnostic.stl");
        var gateRunnerSprueDiagnosticPath = Path.Combine(input.ResolvedOutputDirectory, "GateRunnerSprueDiagnostic.stl");
        var finalReportPath = Path.Combine(input.ResolvedOutputDirectory, "FinalProjectReport.json");

        var warnings = new List<string>
        {
            "Generator pipeline uses cooling, lattice, mold-system, DfAM, and boolean mold block parameters from config.",
            "Generated geometry is preliminary diagnostic or functional-preliminary geometry and is not certified for production manufacturing.",
            "BooleanCavity.stl is generated by voxel boolean subtraction.",
            "BooleanCoreSide.stl and BooleanCavitySide.stl are generated by split mold-block voxel boolean subtraction."
        };

        var partAnalyzer = new PicoPartAnalyzer();
        var partAnalysis = partAnalyzer.AnalyzeBinaryStl(input.ResolvedInputPath, voxelSizeMm);

        if (partAnalysis.PartingPlane is null)
        {
            throw new InvalidOperationException("Part analysis did not produce a parting plane.");
        }

        var diagnosticExporter = new PicoDiagnosticMeshExporter();
        diagnosticExporter.ExportVoxelizedDiagnosticMesh(
            input.ResolvedInputPath,
            diagnosticMeshPath,
            voxelSizeMm);

        var cavityCoreGenerator = new PicoCavityCoreGenerator();
        cavityCoreGenerator.GeneratePreliminary(new CavityCoreGenerationRequest(
            SourcePath: input.ResolvedInputPath,
            OutputDirectory: input.ResolvedOutputDirectory,
            ShrinkageRate: shrinkageRate,
            PartingPlane: partAnalysis.PartingPlane));

        var booleanCavityGenerator = new PicoBooleanCavityGenerator();
        booleanCavityGenerator.Generate(new BooleanCavityGenerationRequest(
            SourcePath: input.ResolvedInputPath,
            OutputDirectory: input.ResolvedOutputDirectory,
            BlockBounds: input.BooleanMoldBlockBounds,
            VoxelSizeMm: voxelSizeMm));

        var booleanSplitter = new PicoBooleanCavityCoreSplitter();
        booleanSplitter.Generate(new BooleanCavityCoreSplitRequest(
            SourcePath: input.ResolvedInputPath,
            OutputDirectory: input.ResolvedOutputDirectory,
            BlockBounds: input.BooleanMoldBlockBounds,
            SplitAxis: ResolveSplitAxis(input, partAnalysis.PartingPlane),
            PartingPlaneOffsetMm: ResolvePartingPlaneOffset(input, partAnalysis.PartingPlane),
            VoxelSizeMm: voxelSizeMm));

        var coolingRequest = CreateCoolingRequest(input);
        var coolingPlanner = new CoolingPlanner();
        var coolingPlan = coolingPlanner.PlanStraightChannels(coolingRequest);

        var coolingExporter = new PicoCoolingDiagnosticExporter();
        coolingExporter.ExportCoolingDiagnostic(
            coolingPlan,
            coolingDiagnosticPath,
            voxelSizeMm);

        var latticeRequest = CreateLatticeRequest(input);
        var latticePlanner = new LatticePlanner();
        var latticePlan = latticePlanner.PlanSimpleGrid(latticeRequest);

        var latticeExporter = new PicoLatticeDiagnosticExporter();
        latticeExporter.ExportLatticeDiagnostic(
            latticePlan,
            latticeDiagnosticPath,
            voxelSizeMm);

        var moldSystemRequest = CreateMoldSystemRequest(input);
        var moldSystemPlanner = new PreliminaryMoldSystemPlanner();
        var moldSystemPlan = moldSystemPlanner.Plan(moldSystemRequest);

        var moldSystemExporter = new PicoMoldSystemDiagnosticExporter();
        moldSystemExporter.ExportMoldSystemDiagnostic(
            moldSystemPlan,
            moldSystemDiagnosticPath,
            voxelSizeMm);
        var gateRunnerSprueInput = GeneratorGateRunnerSpruePlanFactory.CreateInput(input);
        var gateRunnerSpruePlan = GeneratorGateRunnerSpruePlanFactory.Plan(gateRunnerSprueInput);

        var gateRunnerSprueExporter = new PicoGateRunnerSprueDiagnosticExporter();
        gateRunnerSprueExporter.ExportGateRunnerSprueDiagnostic(
            gateRunnerSprueInput,
            gateRunnerSprueDiagnosticPath,
            voxelSizeMm);

        var dfamAnalyzer = new PreliminaryDfAMAnalyzer();
        var dfamReport = dfamAnalyzer.Analyze(CreateDfAMSnapshot(
            input,
            coolingRequest,
            latticeRequest,
            moldSystemRequest));

        var reportBuilder = new FinalReportBuilder();
        var manifest = reportBuilder.CreateStandardManifest(input.ResolvedOutputDirectory);

        var functionalMoldAlpha = GeneratorFunctionalMoldAlphaReportFactory.Create(
            input,
            partAnalysis,
            coolingPlan,
            dfamReport);
        var finalReport = reportBuilder.Build(
            projectName: input.Config.ProjectName,
            manifest: manifest,
            partAnalysis: partAnalysis,
            dfam: dfamReport,
            baseline: new BaselineStatus(
                IsPassing: true,
                TotalTests: 113,
                Summary: "Baseline was passing before Phase 13B generator integration."),
            generatedAtUtc: DateTimeOffset.UtcNow,
            functionalMoldAlpha: functionalMoldAlpha);

        var jsonWriter = new FinalReportJsonWriter();
        jsonWriter.WriteToFile(finalReport, finalReportPath);

        var generatedArtifacts = new[]
        {
            diagnosticMeshPath,
            Path.Combine(input.ResolvedOutputDirectory, "Cavity.stl"),
            booleanCavityPath,
            Path.Combine(input.ResolvedOutputDirectory, "Core.stl"),
            booleanCoreSidePath,
            booleanCavitySidePath,
            coolingDiagnosticPath,
            latticeDiagnosticPath,
            moldSystemDiagnosticPath,
            finalReportPath
        };

        foreach (var artifact in generatedArtifacts)
        {
            if (!File.Exists(artifact))
            {
                throw new FileNotFoundException("Expected generated artifact was not found.", artifact);
            }
        }

        return new GeneratorPipelineRunResult(
            input.Config.ProjectName,
            input.ResolvedOutputDirectory,
            finalReportPath,
            generatedArtifacts,
            warnings);
    }


    private static Core.Parting.PartingAxis ResolveSplitAxis(
        GeneratorPipelineInput input,
        Core.Parting.PartingPlaneResult automaticPartingPlane)
    {
        return input.PartingOverride?.Axis ?? automaticPartingPlane.Axis;
    }

    private static decimal ResolvePartingPlaneOffset(
        GeneratorPipelineInput input,
        Core.Parting.PartingPlaneResult automaticPartingPlane)
    {
        return input.PartingOverride?.OffsetMm ?? Convert.ToDecimal(automaticPartingPlane.PlaneOffsetMm);
    }
    private static CoolingChannelRequest CreateCoolingRequest(GeneratorPipelineInput input)
    {
        return new CoolingChannelRequest(
            OutputDirectory: input.ResolvedOutputDirectory,
            PartSizeXmm: input.Cooling.PartSizeXmm,
            PartSizeYmm: input.Cooling.PartSizeYmm,
            PartSizeZmm: input.Cooling.PartSizeZmm,
            ChannelDiameterMm: input.Cooling.ChannelDiameterMm,
            ChannelSpacingMm: input.Cooling.ChannelSpacingMm,
            MinimumClearanceMm: input.Cooling.MinimumClearanceMm,
            ChannelCount: input.Cooling.ChannelCount);
    }

    private static LatticeRegionRequest CreateLatticeRequest(GeneratorPipelineInput input)
    {
        return new LatticeRegionRequest(
            RegionName: input.Lattice.RegionName,
            OutputDirectory: input.ResolvedOutputDirectory,
            MinXmm: input.Lattice.MinXmm,
            MinYmm: input.Lattice.MinYmm,
            MinZmm: input.Lattice.MinZmm,
            MaxXmm: input.Lattice.MaxXmm,
            MaxYmm: input.Lattice.MaxYmm,
            MaxZmm: input.Lattice.MaxZmm,
            CellSizeMm: input.Lattice.CellSizeMm,
            BeamRadiusMm: input.Lattice.BeamRadiusMm,
            TargetRelativeDensity: input.Lattice.TargetRelativeDensity);
    }

    private static MoldSystemRequest CreateMoldSystemRequest(GeneratorPipelineInput input)
    {
        return new MoldSystemRequest(
            OutputDirectory: input.ResolvedOutputDirectory,
            PartSizeXmm: input.MoldSystem.PartSizeXmm,
            PartSizeYmm: input.MoldSystem.PartSizeYmm,
            PartSizeZmm: input.MoldSystem.PartSizeZmm,
            MoldMarginMm: input.MoldSystem.MoldMarginMm,
            EjectorPinDiameterMm: input.MoldSystem.EjectorPinDiameterMm,
            EjectorPinCount: input.MoldSystem.EjectorPinCount,
            VentWidthMm: input.MoldSystem.VentWidthMm,
            VentDepthMm: input.MoldSystem.VentDepthMm,
            InsertClearanceMm: input.MoldSystem.InsertClearanceMm);
    }

    private static DfAMInputSnapshot CreateDfAMSnapshot(
        GeneratorPipelineInput input,
        CoolingChannelRequest cooling,
        LatticeRegionRequest lattice,
        MoldSystemRequest moldSystem)
    {
        return new DfAMInputSnapshot(
            MinimumWallThicknessMm: input.DfAM.MinimumWallThicknessMm,
            RecommendedMinimumWallThicknessMm: input.DfAM.RecommendedMinimumWallThicknessMm,
            CoolingMinimumClearanceMm: cooling.MinimumClearanceMm,
            CoolingChannelDiameterMm: cooling.ChannelDiameterMm,
            LatticeBeamRadiusMm: lattice.BeamRadiusMm,
            LatticeCellSizeMm: lattice.CellSizeMm,
            EjectorPinDiameterMm: moldSystem.EjectorPinDiameterMm,
            UsesPreliminaryGeometry: input.DfAM.UsesPreliminaryGeometry);
    }
}