using System.Numerics;
using PicoMoldForge.Core.CavityCore;
using PicoMoldForge.PicoGK.Runtime;
using PicoLibrary = global::PicoGK.Library;
using PicoMesh = global::PicoGK.Mesh;

namespace PicoMoldForge.PicoGK.CavityCore;

public sealed class PicoCavityCoreGenerator
{
    private readonly ShrinkageCompensator shrinkageCompensator;

    public PicoCavityCoreGenerator()
        : this(new ShrinkageCompensator())
    {
    }

    public PicoCavityCoreGenerator(ShrinkageCompensator shrinkageCompensator)
    {
        this.shrinkageCompensator = shrinkageCompensator;
    }

    public CavityCoreGenerationResult GeneratePreliminary(CavityCoreGenerationRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var validationErrors = request.Validate();

        if (validationErrors.Count > 0)
        {
            throw new ArgumentException(
                "Invalid cavity/core generation request: " + string.Join(" ", validationErrors),
                nameof(request));
        }

        var resolvedSourcePath = Path.GetFullPath(request.SourcePath);
        var resolvedOutputDirectory = Path.GetFullPath(request.OutputDirectory);

        if (!File.Exists(resolvedSourcePath))
        {
            throw new FileNotFoundException("Source STL file was not found.", resolvedSourcePath);
        }

        Directory.CreateDirectory(resolvedOutputDirectory);

        var cavityPath = Path.Combine(resolvedOutputDirectory, "Cavity.stl");
        var corePath = Path.Combine(resolvedOutputDirectory, "Core.stl");

        var shrinkage = shrinkageCompensator.CalculateUniformScale(request.ShrinkageRate);
        var scale = Convert.ToSingle(shrinkage.ScaleFactor);
        var scaleVector = new Vector3(scale, scale, scale);

        PicoGkTaskRunner.Run(() =>
        {
            var sourceMesh = PicoMesh.mshFromStlFile(
                resolvedSourcePath,
                default,
                1.0f,
                null,
                PicoLibrary.oLibrary());

            try
            {
                using var cavityMesh = sourceMesh.mshCreateTransformed(
                    scaleVector,
                    Vector3.Zero);

                using var coreMesh = sourceMesh.mshCreateTransformed(
                    scaleVector,
                    CreatePreliminaryCoreOffset(request));

                cavityMesh.SaveToStlFile(
                    cavityPath,
                    PicoMesh.EStlUnit.MM,
                    null,
                    1.0f);

                coreMesh.SaveToStlFile(
                    corePath,
                    PicoMesh.EStlUnit.MM,
                    null,
                    1.0f);

                return true;
            }
            finally
            {
                sourceMesh.Dispose();
            }
        });

        var artifacts = new[]
        {
            new CavityCoreArtifact(
                CavityCoreArtifactKind.Cavity,
                cavityPath,
                "Preliminary shrinkage-compensated cavity diagnostic STL generated by PicoGK."),
            new CavityCoreArtifact(
                CavityCoreArtifactKind.Core,
                corePath,
                "Preliminary shrinkage-compensated core diagnostic STL generated by PicoGK with deterministic opening-direction offset.")
        };

        var warnings = new[]
        {
            "Phase 5B generates preliminary diagnostic cavity/core STL files only.",
            "Generated Cavity.stl and Core.stl are not production mold geometry.",
            "Shrinkage compensation is currently a uniform scale factor.",
            "Core geometry is represented as a deterministic preliminary offset mesh, not a true mold core.",
            "No shutoff surfaces, parting-line optimization, side actions, inserts, draft validation, or manufacturability certification are implemented yet."
        };

        return new CavityCoreGenerationResult(
            IsSuccessful: true,
            ShrinkageScaleFactor: shrinkage.ScaleFactor,
            Artifacts: artifacts,
            Warnings: warnings);
    }

    private static Vector3 CreatePreliminaryCoreOffset(CavityCoreGenerationRequest request)
    {
        var direction = request.PartingPlane?.OpeningDirection;

        if (direction is null || direction.IsZero)
        {
            return Vector3.Zero;
        }

        var offsetDistanceMm = 2.0f;

        return new Vector3(
            direction.X * offsetDistanceMm,
            direction.Y * offsetDistanceMm,
            direction.Z * offsetDistanceMm);
    }
}